---
- name: Playbook using condition
  hosts: ubuntu
  vars:
    package: apache2
    require: "yes"
  tasks: 
    - name: Service Up
      service: 
        name: "{{ package }}"
        state: restarted
      when: require  == "yes"