- name: Playbook for copy
  hosts: ubuntu
  tasks:  
    - name: Copy file
      copy:
        src: ./inventory
        dest: /etc  

    - name: delete file
      file:
        path: /etc/inventory
        state: absent

    - name: adding file
      file:
        path: /etc/devops.txt
        state: touch