---
- name: playbook for error handling
  hosts: ubuntu
  tasks:
    - name: install apachex
      apt: 
        name: apachex
        state: present 
      ignore_errors: true

    - name: error command
      commmand: lsl
      register: gagal
      failed_when: gagal.rc >= 2