---
- name: ansible forking
  hosts: all
  tasks: 
    - name: install awscli
      yum:
        name: awscli
        state: present
      when: ansible_os_family == "RedHat"
    - name: install awscli
      apt:
        name: awscli
        state: present
      when: ansible_os_family == "Debian"