---
- name: Playbook for handlers
  hosts: ubuntu
  tasks:
    - name: installing apache2
      apt: 
        name: apache2
        state: latest
      notify: 
        - Restart apache2
  handlers:
    - name: Restart apache
      service: 
        name: apache2
        state: started