---
- name: Jinja2 Templating
  hosts: localhost
  vars:
    new_list: 
      - 10
      - 30
      - 20
  tasks:
    - name: find max 
      debug:
        msg: "{{ new_list | max }}"
    - name: find min 
      debug:
        msg: "{{ new_list | min }}"
    
- name: Jinja2 Templating
  hosts: webserver
  vars:
    your_name: "DevOps"
  tasks:
    - name: print uppercase 
      debug:
        msg: "{{ your_name | upper }}"
    - name: print lowercase 
      debug:
        msg: "{{ your_name | lower }}"

#- name: Jinja2 Templating
#  hosts: webserver
#  vars:
#    color: "Orange"
#  tasks:
#    - name: print uppercase 
#      debug:
#        msg: "{{ color | replace('Orange:Yellow') }}"
#    - name: print lowercase 
#      debug:
#        msg: "{{ your_name | lower }}"

- name: Jinja2 Templating
  hosts: webserver
  tasks:
    - name: create random number
      debug:
        msg: "{{ 100 | random }}"

- name: Jinja2 Templating
  hosts: webserver
  tasks:
    - name: create basename 
      debug:
        msg: "{{ '/etc/ansible/ansible.cfg' | basename }}"
    - name: create dirname
      debug:
        msg: "{{ '/etc/ansible/ansible.cfg' | dirname }}"