---
- name: Playbook using with_items looping
  hosts: ubuntu
  tasks:
    - name: Installing all requirement packets
      yum: 
        name: {{ item }}
        state: present
      with_items:
        - python3
        - dnsutils
        - nginx