---
- name: Playbook
  hosts: webserver
  tasks:
    - name: Install the Epel Repository
      ansible.builtin.yum:
        name: epel-release
        state: present 
    - name: Install the nginx
      ansible.builtin.yum:
        name: nginx
        state: present  
    - name: Install the dnsutils
      ansible.builtin.yum:
        name: dns-utils
        state: present  

---
- name: Playbook 2 
  hosts: ubuntu
  tasks:  
    - name: Install the nginx
      apt:
        name: nginx
        state: present  
    - name: Install the dnsutils
      apt:
        name: dnsutils
        state: present 