---
- name: Playbook
  hosts: webserver
  tasks:
    - name: Install the Epel Repository
      ansible.builtin.yum:
        name: epel-release
        state: present 
    - name: Install the nginx
      ansible.builtin.yum:
        name: nginx
        state: present  
    - name: Install the dnsutils
      ansible.builtin.yum:
        name: dns-utils
        state: present  