---
- name: Playbook1
  hosts: host1,host2
  tasks:
    - name: Install the python3
      ansible.builtin.yum:
        name: python3
        state: present      

- name: Playbook2
  hosts: host1,host2
  tasks:
    - name: Install the NGINX
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Copy file config
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Start NGINX
      service:
        name: nginx
        state: restarted
        enabled: yes




  #handlers:
  #- name: Restart Nginx
  #  service:
  #    name: nginx
  #   state: restarted