---
- name: Playbook1
  hosts: host1,host2
  tasks:
    - name: Install the python3
      ansible.builtin.yum:
        name: python3
        state: present
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Restart Nginx

  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted