---
- name: Playbook1
  hosts: webserver
  vars:
    package: apache2
  tasks:
    - name: Install the apache2
      ansible.builtin.yum:
        name: "{{ package }}"
        state: present
   - name: Install the apache2
      ansible.builtin.service:
        name: "{{ package }}"
        state: started