---
- name: playbook for install
  hosts: webserver
  tasks:
    - name: Uninstall awscli
      yum:
        name: awscli
        state: absent
    - name: install awscli
      yum:
        name: awscli
        state: present

- name: playbook for install
  hosts: ubuntu
  tasks:
    - name: install dnsutils
      apt:
        name: dnsutils
        state: present
