---
- name: Playbook for install git
  hosts: host1
  tasks:
    - name: Installing git
      ansible.builtin.yum:
        name: git
        state: present

- name: Playbook for install python3
  hosts: host1,host3
  tasks:
    - name: Installing python3
      ansible.builtin.yum:
        name: python3
        state: present

- name: Playbook for install webserver
  hosts: all
  tasks:
    - name: Installing python3
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Installing python3
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"


